// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sstv.Outbox.Sample;

#nullable disable

namespace Sstv.Outbox.Sample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sstv.Outbox.Sample.EfOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<byte[]>("Headers")
                        .HasColumnType("bytea")
                        .HasColumnName("headers");

                    b.Property<DateTimeOffset?>("RetryAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_after");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_ef_outbox_items");

                    b.HasIndex("CreatedAt", "RetryAfter", "Status")
                        .HasDatabaseName("ix_ef_outbox_items_created_at_retry_after_status");

                    b.ToTable("ef_outbox_items", (string)null);
                });

            modelBuilder.Entity("Sstv.Outbox.Sample.KafkaEfOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Headers")
                        .HasColumnType("json")
                        .HasColumnName("headers");

                    b.Property<byte[]>("Key")
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("RetryAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_after");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kafka_ef_outbox_items");

                    b.ToTable("kafka_ef_outbox_items", (string)null);
                });

            modelBuilder.Entity("Sstv.Outbox.Sample.KafkaEfOutboxItemWithPriority", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Headers")
                        .HasColumnType("json")
                        .HasColumnName("headers");

                    b.Property<byte[]>("Key")
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("RetryAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retry_after");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Topic")
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.Property<byte[]>("Value")
                        .HasColumnType("bytea")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_kafka_ef_outbox_item_with_priorities");

                    b.HasIndex("Priority", "RetryAfter", "Status")
                        .HasDatabaseName("ix_kafka_ef_outbox_item_with_priorities_priority_retry_after_s");

                    b.ToTable("kafka_ef_outbox_item_with_priorities", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
